version: '3.8'

services:
  chat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: chat
    expose:
      - "8080"
    command: ["serve"]

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - chat
